FROM ghcr.io/rocker-org/devcontainer/r-ver:4.5

# Architecture-specific variable (built in Docker BuildKit)
ARG TARGETARCH

# Install quarto-cli and the orange-book extension
RUN wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.9.35/quarto-1.9.35-linux-${TARGETARCH}.deb && \
    dpkg -i quarto-1.9.35-linux-${TARGETARCH}.deb && \
    rm quarto-1.9.35-linux-${TARGETARCH}.deb

# Adding R packages
RUN install2.r --error -n4 ergm.multi quarto data.table netplot ggplot2 gridExtra texreg ergmito ggrepel patchwork ggridges ggExtra

RUN apt-get update && apt-get install -y --no-install-recommends \
    libglpk-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

CMD ["bash"]
