---
title: "Bootstrapping ERGMs"
format: html
  # pdf:
  #   extra_dependencies:
  #     - pdflscape
  #     - rotating
  #     - tabularx
  #     - booktabs
  #     - geometry
  #     - graphicx
editor_options: 
  markdown: 
    wrap: 80
date: 2023-08-26
author:
  - Chong Zhang
  - George G. Vega Yon
date-modified: 2025-01-03
embed-resources: true
---

8/28/2023

```{r}
source("models/helpers.R")
load('data/network93_f2.RData')
fits <- readRDS("models/03-pooled-ergms-final-results.rds")
```

## Evaluating in the final model


```{r}
# Naive 9 cluster (for now)
cl <- parallel::makeForkCluster(40)

set.seed(333)
ans <- boot_ergm(
  networks = networks,
  ergm_formula =
    Networks(nets) ~ N(~edges, ~I(log(n_patients) - mean(log(n_patients))) + 
    I(log(n_hcp) - mean(log(n_hcp)))) + b1factor("type", levels = -3) + 
    gwb1dsp(fixed = FALSE, cutoff = 100) + b2factor("dialysis") + 
    b2factor("wound_care") + b2factor("bedridden") + b2factor("ventilator") + 
    b2factor("mdro") + b2nodematch("diabetes", alpha = 0.25, 
    diff = TRUE, levels = 2) + b2nodematch("mdro", alpha = 0.25, 
    diff = TRUE, levels = 2) + b2nodematch("ventilator", alpha = 0.25, 
    diff = TRUE, levels = 2) + b2nodematch("wound_care", alpha = 0.25, 
    diff = TRUE, levels = 2) + b2nodematch("bedridden", alpha = 0.25, 
    diff = TRUE, levels = 2) + b1nodematch("type", alpha = 0.25, 
    diff = TRUE) + offset(b1degree(0)) + offset(b2degree(0)),
  control = control.ergm(
    seed = 1123,
    # fits$gwdsp_with_log_patients |> coef() |> unname() |> dput()
    init = c(
      -0.229774411182076, -0.928865362739409, 0.582187512066458, 
      0.190219755730461, 0.38012816966676, -0.658484355279783,
      0.070170286661905, -1.07822339150196, 0.837596079108853, 
      -0.0513051848410123, 0.185363934047775, 0.1796971437691,
      0.382103632278962, 0.0898188937799372, -0.0153806422634283,
      -0.168823821727854, -0.121699946156744, -0.00762496361500502, 
      -0.0486631133521477, -0.96254189061651, -2.18000463775114,
      -0.251900054362114, 0.878432180573765, -1.56969270927592,
      -Inf, -Inf
    ),
    main.method = "Stochastic-Approximation",
    SA.samplesize = 1024 * 8,
    SA.burnin = 1024 * 64, # Double
    SA.interval = 1024 * 8
  ),
  offset.coef = c(-Inf, -Inf),
  nboot = 200,
  cl = cl,
  cache = "models/04b-boot-ergms-cache"
)
parallel::stopCluster(cl)

```

## Processing the bootstrap results


```{r}
# Listing all the bootstrap results
boot_res <- list.files(
  "models/04b-boot-ergms-cache",
  pattern = "\\.rds$",
  full.names = TRUE
  ) |> 
  lapply(readRDS) |>
  do.call(what = rbind)

# Generating a regression table
boot_res_mean <- apply(boot_res, 2, mean, na.rm = TRUE)
boot_res_sd <- apply(boot_res, 2, sd, na.rm = TRUE)

# Computing the pvalues
naive_fit <- fits$gwdsp_with_log_patients
pvalues <- 2 * (1 - pnorm(abs(coef(naive_fit)) / boot_res_sd))

# Reading the results from the MC-MLE bootstrap
boot_mcmle_res <- list.files(
  "models/04-boot-ergms-cache",
  pattern = "\\.rds$",
  full.names = TRUE
  ) |> 
  lapply(readRDS) |>
  do.call(what = rbind)

# Generating a regression table
boot_mcmle_res_mean <- apply(boot_mcmle_res, 2, mean, na.rm = TRUE)
boot_mcmle_res_sd <- apply(boot_mcmle_res, 2, sd, na.rm = TRUE)

# Computing the pvalues
pvalues_mcmle <- 2 * (1 - pnorm(abs(coef(naive_fit)) / boot_mcmle_res_sd))

texreg::screenreg(
  list(
    'Naive model'=naive_fit,
    'SA Bootstrap model'=naive_fit,
    'MC-MLE Bootstrap model'=naive_fit
    ),
  override.se = list(NULL, boot_res_sd, boot_mcmle_res_sd),
  override.pvalues = list(NULL, pvalues, pvalues_mcmle),
  single.row = TRUE
)
```



```{r}
texreg::htmlreg(
  file = "models/04b-boot-ergms-results.html",
  list(
    'Naive model'=naive_fit,
    'Bootstrap model'=naive_fit
    ),
  override.se = list(NULL, boot_res_sd),
  override.pvalues = list(NULL, pvalues),
  single.row = TRUE
)

saveRDS(
  list(
    bootstrap_results = boot_res,
    bootstrap_means = boot_res_mean,
    bootstrap_sds = boot_res_sd,
    pvalues = pvalues,
    naive_fit = naive_fit
  ),
  file = "models/04b-boot-ergms-results.rds"
)
```

